import Navbar, { StickyNavbar } from "./components/shared/Nav";
import "./globals.css";
import { Inter } from "next/font/google";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { library } from "@fortawesome/fontawesome-svg-core";

// import your icons
import { faCode, faHighlighter } from "@fortawesome/free-solid-svg-icons";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Petadopt",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StickyNavbar />
        {children}
      </body>
    </html>
  );
}
